# Generated by Django 5.2.2 on 2025-06-13 15:02

import Shipment.models
import Shipment.override_existing
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('number', models.BigAutoField(db_column='no', primary_key=True, serialize=False)),
                ('shipment_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('barcode', models.ImageField(blank=True, db_column='barcode', storage=Shipment.override_existing.OverrideExisting(), upload_to=Shipment.models.barcode_path)),
                ('colorpick', models.CharField(blank=True, db_column='color_status', max_length=50)),
                ('colordiv', models.CharField(blank=True, db_column='color_div', default='black', max_length=50)),
                ('kantor_id', models.CharField(blank=True, db_column='kantor_id', max_length=100)),
                ('insert_org', models.CharField(blank=True, db_column='insert_org', max_length=100)),
                ('correct_org', models.CharField(blank=True, db_column='correct_org', max_length=100)),
                ('reg_date', models.DateTimeField(auto_now=True, db_column='regdate')),
                ('company', models.CharField(blank=True, choices=[('GOLTENS', 'GOLTENS'), ('MAN', 'MAN'), ('JW', 'JW'), ('CMSHIP', 'CMSHIP'), ('MARUBISHI', 'MARUBISHI'), ('STX', 'STX'), ('SUNRIO', 'SUNRIO'), ('KNK', 'KNK'), ('EUCO', 'EUCO'), ('SHI OCEAN', 'SHI OCEAN'), ('GLOVIS', 'GLOVIS'), ('KSS', 'KSS'), ('GOWIN', 'GOWIN'), ('INTERGIS', 'INTERGIS'), ('SUNAMI', 'SUNAMI'), ('INTERGIS', 'INTERGIS'), ('SUNAMI', 'SUNAMI'), ('보성상사', '보성상사'), ('이강공사', '이강공사'), ('오션마린', '오션마린'), ('CENTRA', 'CENTRA'), ('POSSM', 'POSSM'), ('DORVAL', 'DORVAL'), ('SAEHAN', 'SAEHAN'), ('FORTUNE WILL', 'FORTUNE WILL'), ('SEOYANG', 'SEOYANG'), ('KLCSM', 'KLCSM'), ('DAN MO', 'DAN MO')], db_column='company', max_length=200)),
                ('vessel', models.CharField(blank=True, db_column='vessel', max_length=200)),
                ('by', models.CharField(blank=True, db_column='by1', max_length=100)),
                ('BLno', models.CharField(blank=True, db_column='blno', max_length=200)),
                ('ASKno', models.CharField(blank=True, db_column='askno', max_length=200)),
                ('docs', models.TextField(blank=True, db_column='doc', max_length=1000)),
                ('POno', models.TextField(blank=True, db_column='pono', max_length=1000)),
                ('c_packing', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], db_column='c_packing', default='NO', max_length=50)),
                ('supplier', models.TextField(blank=True, db_column='supplier', max_length=1000)),
                ('quanty', models.CharField(blank=True, db_column='qty', max_length=50)),
                ('unit', models.CharField(blank=True, db_column='unit', max_length=50)),
                ('size', models.TextField(blank=True, db_column='size', max_length=200)),
                ('weight', models.CharField(blank=True, db_column='weight', max_length=200)),
                ('in_date', models.DateField(blank=True, db_column='in1', default=django.utils.timezone.now, max_length=50, null=True)),
                ('warehouse', models.CharField(blank=True, db_column='whouse', max_length=200)),
                ('warehouse2', models.CharField(blank=True, db_column='whouse2', max_length=200)),
                ('last_whouse', models.CharField(blank=True, db_column='last_whouse', max_length=200)),
                ('wh_timestamp', models.DateTimeField(blank=True, db_column='wh_timestamp1', max_length=100, null=True)),
                ('wh_timestamp2', models.DateTimeField(blank=True, db_column='wh_timestamp2', max_length=100, null=True)),
                ('port', models.CharField(blank=True, db_column='port', max_length=200)),
                ('out_date', models.DateField(blank=True, db_column='out1', max_length=50, null=True)),
                ('remark', models.TextField(blank=True, db_column='remark', max_length=1000)),
                ('memo', models.TextField(blank=True, db_column='memo', max_length=1000)),
                ('image', models.ImageField(blank=True, db_column='img', default='', max_length=1000, null=True, storage=Shipment.override_existing.OverrideExisting(), upload_to=Shipment.models.image_path)),
                ('image1', models.ImageField(blank=True, db_column='img1', default='', max_length=1000, null=True, storage=Shipment.override_existing.OverrideExisting(), upload_to=Shipment.models.image_path)),
                ('image2', models.ImageField(blank=True, db_column='img2', default='', max_length=1000, null=True, storage=Shipment.override_existing.OverrideExisting(), upload_to=Shipment.models.image_path)),
                ('pdf_file', models.FileField(blank=True, db_column='pdf', default='', max_length=1000, null=True, storage=Shipment.override_existing.OverrideExisting(), upload_to=Shipment.models.pdf_path)),
                ('division', models.CharField(blank=True, choices=[('D', 'D'), ('B', 'B'), ('L', 'L')], db_column='division', max_length=50)),
                ('flag_status', models.CharField(blank=True, choices=[('BLANK', 'BLANK'), ('STAY', 'STAY'), ('START', 'START'), ('COMPLETED', 'COMPLETED')], db_column='flg', max_length=50)),
                ('job_number', models.CharField(blank=True, db_column='jobno', max_length=200)),
                ('work', models.CharField(blank=True, db_column='work', max_length=50)),
                ('work_regdate', models.DateTimeField(blank=True, db_column='work_regdate', max_length=100, null=True)),
            ],
            options={
                'db_table': 'pla_databoard',
            },
        ),
        migrations.CreateModel(
            name='ShipmentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.CharField(blank=True, choices=[('SL', 'SL'), ('KIM-IGS', 'KIM-IGS'), ('ICN-IGS', 'ICN-IGS'), ('ICN-CSW', 'ICN-CSW'), ('PUS-CSW', 'PUS-CSW'), ('SHA', 'SHA'), ('OSA', 'OSA'), ('RTM', 'RTM')], max_length=200)),
                ('flag_status', models.CharField(blank=True, choices=[('BLANK', 'BLANK'), ('STAY', 'STAY'), ('START', 'START'), ('COMPLETED', 'COMPLETED')], max_length=50)),
                ('in_date', models.DateField(blank=True, null=True)),
                ('out_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('changed_by', models.CharField(blank=True, max_length=100)),
                ('remark', models.TextField(blank=True, max_length=1000)),
                ('movement_type', models.CharField(blank=True, choices=[('STATUS', 'Status Change'), ('WAREHOUSE', 'Warehouse Change'), ('DATE', 'Date Change'), ('OTHER', 'Other')], max_length=50)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='Shipment.shipment')),
            ],
            options={
                'db_table': 'pla_shipment_movement',
                'ordering': ['-timestamp'],
            },
        ),
    ]
