# Generated by Django 5.2.2 on 2025-06-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentmovement',
            name='flag_statrus',
            field=models.CharField(blank=True, choices=[('START', 'Start'), ('STAY', 'Stay'), ('COMPLETED', 'Completed'), ('BLANK', 'Blank')], default='BLANK', max_length=50),
        ),
        migrations.AddField(
            model_name='shipmentmovement',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('VESSEL', 'Vessel'), ('AIRPLANE', 'Airplane'), ('TRUCK', 'Truck'), ('PORT', 'Port'), ('TRAIN', 'Train'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentmovement',
            name='movement_type',
            field=models.CharField(blank=True, choices=[('STATUS', 'Status'), ('WAREHOUSE', 'Warehouse'), ('LOCATION_UPDATE', 'Location Update'), ('DATE', 'Date'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
