# Generated by Django 5.2.2 on 2025-06-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0002_shipmentmovement_flag_statrus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentmovement',
            name='remark',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
