# Generated by Django 5.2.2 on 2025-06-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0003_alter_shipmentmovement_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Shipment.shipment')),
            ],
            options={
                'unique_together': {('shipment',)},
            },
        ),
    ]
