# Generated by Django 5.2.2 on 2025-09-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0004_shipmentevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
