# Generated by Django 5.2.2 on 2025-09-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0005_shipment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentmovement',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
