# Generated by Django 5.2.2 on 2025-09-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0006_alter_shipmentmovement_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentmovement',
            name='warehouse',
            field=models.CharField(blank=True, choices=[('SL', 'SL'), ('KIM-IGS', 'KIM-IGS'), ('ICN-IGS', 'ICN-IGS'), ('ICN-CSW', 'ICN-CSW'), ('PUS-CSW', 'PUS-CSW'), ('SHA', 'SHA'), ('OSA', 'OSA'), ('RTM', 'RTM')], max_length=200, null=True),
        ),
    ]
