# Generated by Django 5.2.2 on 2025-09-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0007_alter_shipmentmovement_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='warehouse',
            field=models.CharField(blank=True, db_column='whouse', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='warehouse2',
            field=models.CharField(blank=True, db_column='whouse2', max_length=200, null=True),
        ),
    ]
