# Generated by Django 5.2.2 on 2025-09-17 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0008_alter_shipment_warehouse_alter_shipment_warehouse2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='shipment_files/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Shipment.shipment')),
            ],
        ),
    ]
