# Generated by Django 5.2.2 on 2025-09-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0009_shipmentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='ASKno',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='BLno',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='POno',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='job_number',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='memo',
        ),
        migrations.AddField(
            model_name='shipment',
            name='EXP_BL',
            field=models.CharField(blank=True, db_column='exp_bl', max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='IMP_BL',
            field=models.CharField(blank=True, db_column='imp_bl', max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='Order_No',
            field=models.TextField(blank=True, db_column='order_no', max_length=1000),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='c_packing',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], db_column='c_packing', max_length=50, null=True),
        ),
    ]
