# Generated by Django 5.2.2 on 2025-09-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0010_remove_shipment_askno_remove_shipment_blno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='c_packing',
            field=models.CharField(blank=True, choices=[('', ''), ('YES', 'YES'), ('NO', 'NO')], db_column='c_packing', default='', max_length=50, null=True),
        ),
    ]
