# Generated by Django 5.2.2 on 2025-09-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0015_alter_shipment_c_packing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='c_packing',
            field=models.CharField(blank=True, choices=[('', '-------'), ('YES', 'YES'), ('NO', 'NO')], db_column='c_packing', max_length=50, null=True),
        ),
    ]
