# Generated by Django 5.2.2 on 2025-09-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0017_alter_shipment_c_packing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(blank=True, choices=[], db_column='company', max_length=200),
        ),
    ]
