# Generated by Django 5.2.2 on 2025-09-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0018_alter_shipment_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(blank=True, choices=[('GOLTENS', 'GOLTENS'), ('MAN', 'MAN'), ('JW', 'JW'), ('CMSHIP', 'CMSHIP'), ('MARUBISHI', 'MARUBISHI'), ('STX', 'STX'), ('SUNRIO', 'SUNRIO'), ('KNK', 'KNK'), ('EUCO', 'EUCO'), ('SHI OCEAN', 'SHI OCEAN'), ('GLOVIS', 'GLOVIS'), ('KSS', 'KSS'), ('GOWIN', 'GOWIN'), ('INTERGIS', 'INTERGIS'), ('SUNAMI', 'SUNAMI'), ('INTERGIS', 'INTERGIS'), ('SUNAMI', 'SUNAMI'), ('보성상사', '보성상사'), ('이강공사', '이강공사'), ('오션마린', '오션마린'), ('CENTRA', 'CENTRA'), ('POSSM', 'POSSM'), ('DORVAL', 'DORVAL'), ('SAEHAN', 'SAEHAN'), ('FORTUNE WILL', 'FORTUNE WILL'), ('SEOYANG', 'SEOYANG'), ('KLCSM', 'KLCSM'), ('DAN MO', 'DAN MO')], db_column='company', max_length=200),
        ),
    ]
