# Generated by Django 5.2.2 on 2025-10-16 11:07

import Shipment.models
import Shipment.override_existing
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0025_alter_shipment_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('remark_staff', models.TextField(blank=True)),
                ('barcode', models.ImageField(blank=True, db_column='barcode', storage=Shipment.override_existing.OverrideExisting(), upload_to=Shipment.models.barcode_path)),
                ('colorpick', models.CharField(blank=True, db_column='color_status', max_length=50)),
                ('colordiv', models.CharField(blank=True, db_column='color_div', default='black', max_length=50)),
                ('kantor_id', models.CharField(blank=True, db_column='kantor_id', max_length=100)),
                ('insert_org', models.CharField(blank=True, db_column='insert_org', max_length=100)),
                ('correct_org', models.CharField(blank=True, db_column='correct_org', max_length=100)),
                ('company', models.CharField(blank=True, db_column='company', max_length=200)),
                ('vessel', models.CharField(blank=True, db_column='vessel', max_length=200)),
                ('by', models.CharField(blank=True, db_column='by1', max_length=100)),
                ('IMP_BL', models.CharField(blank=True, db_column='imp_bl', max_length=200)),
                ('docs', models.TextField(blank=True, db_column='doc', max_length=1000)),
                ('Order_No', models.TextField(blank=True, db_column='order_no', max_length=1000)),
                ('c_packing', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], db_column='c_packing', max_length=50, null=True)),
                ('supplier', models.TextField(blank=True, db_column='supplier', max_length=1000)),
                ('quanty', models.CharField(blank=True, db_column='qty', max_length=50)),
                ('unit', models.CharField(blank=True, db_column='unit', max_length=50)),
                ('size', models.TextField(blank=True, db_column='size', max_length=200)),
                ('weight', models.CharField(blank=True, db_column='weight', max_length=200)),
                ('in_date', models.DateField(blank=True, db_column='in1', default=django.utils.timezone.now, max_length=50, null=True)),
                ('warehouse', models.CharField(blank=True, db_column='whouse', max_length=200, null=True)),
                ('warehouse2', models.CharField(blank=True, db_column='whouse2', max_length=200, null=True)),
                ('last_whouse', models.CharField(blank=True, db_column='last_whouse', max_length=200)),
                ('wh_timestamp', models.DateTimeField(blank=True, db_column='wh_timestamp1', max_length=100, null=True)),
                ('wh_timestamp2', models.DateTimeField(blank=True, db_column='wh_timestamp2', max_length=100, null=True)),
                ('port', models.CharField(blank=True, db_column='port', max_length=200)),
                ('out_date', models.DateField(blank=True, db_column='out1', max_length=50, null=True)),
                ('remark', models.TextField(blank=True, db_column='remark', max_length=1000)),
                ('image', models.ImageField(blank=True, db_column='img', default='', max_length=1000, null=True, storage=Shipment.override_existing.OverrideExisting(), upload_to=Shipment.models.image_path)),
                ('image1', models.ImageField(blank=True, db_column='img1', default='', max_length=1000, null=True, storage=Shipment.override_existing.OverrideExisting(), upload_to=Shipment.models.image_path)),
                ('image2', models.ImageField(blank=True, db_column='img2', default='', max_length=1000, null=True, storage=Shipment.override_existing.OverrideExisting(), upload_to=Shipment.models.image_path)),
                ('pdf_file', models.FileField(blank=True, db_column='pdf', default='', max_length=1000, null=True, storage=Shipment.override_existing.OverrideExisting(), upload_to=Shipment.models.pdf_path)),
                ('division', models.CharField(blank=True, choices=[('D', 'D'), ('B', 'B'), ('L', 'L')], db_column='division', max_length=50)),
                ('flag_status', models.CharField(blank=True, choices=[('BLANK', 'BLANK'), ('STAY', 'STAY'), ('START', 'START'), ('COMPLETED', 'COMPLETED')], db_column='flg', max_length=50)),
                ('EXP_BL', models.CharField(blank=True, db_column='exp_bl', max_length=200)),
                ('work', models.CharField(blank=True, db_column='work', max_length=50)),
                ('work_regdate', models.DateTimeField(blank=True, db_column='work_regdate', max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pla_pending_shipments',
            },
        ),
    ]
