# Generated by Django 5.2.2 on 2025-10-16 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0027_delete_pendingshipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Company Name')),
                ('vessel', models.CharField(max_length=100, verbose_name='Vessel Name')),
                ('supplier', models.CharField(max_length=100, verbose_name='Supplier Name')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity (Units)')),
                ('weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Weight (Tons)')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Size/Dimensions')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (Processed)'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50, verbose_name='Approval Status')),
                ('approved_shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_request', to='Shipment.shipment', verbose_name='Final Shipment Link')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Submitting Customer')),
            ],
            options={
                'verbose_name': 'Pending Shipment Request',
                'verbose_name_plural': 'Pending Shipment Requests',
                'db_table': 'sl_pending_shipments',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
