# Generated by Django 5.2.2 on 2025-10-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0028_pendingshipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingShipment',
        ),
    ]
