# Generated by Django 5.2.2 on 2025-10-16 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0029_delete_pendingshipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200)),
                ('vessel', models.CharField(blank=True, max_length=200)),
                ('supplier', models.TextField(blank=True, max_length=1000)),
                ('quanty', models.CharField(blank=True, max_length=50)),
                ('weight', models.CharField(blank=True, max_length=200)),
                ('size', models.TextField(blank=True, max_length=200)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sl_pending_shipments',
                'ordering': ['-submission_date'],
            },
        ),
    ]
