# Generated by Django 5.2.2 on 2025-12-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0030_pendingshipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
