# Generated by Django 5.2.2 on 2025-12-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0031_alter_shipment_shipment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='size',
            field=models.TextField(blank=True, db_column='size', max_length=1000),
        ),
    ]
