# Generated by Django 5.2.2 on 2025-12-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0032_alter_shipment_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
