# Generated by Django 5.2.2 on 2025-06-13 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userID', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='AccountID')),
                ('rawPassword', models.CharField(max_length=30, verbose_name='Password')),
                ('email', models.CharField(blank=True, max_length=30, verbose_name='Email')),
                ('companyName', models.CharField(blank=True, max_length=30, verbose_name='Company')),
                ('supplierName', models.CharField(blank=True, max_length=30, verbose_name='Supplier')),
                ('vesselList', models.TextField(blank=True, max_length=2000, verbose_name='Vessel List')),
                ('permission', models.CharField(choices=[('Read Only', 'Read Only'), ('Read + Modify', 'Read + Modify')], default='Read Only', max_length=30, verbose_name='Permission')),
                ('isOpr', models.BooleanField(default=False, verbose_name='Is Operator')),
                ('isSpl', models.BooleanField(default=False, verbose_name='Is Supplier')),
                ('isCpn', models.BooleanField(default=False, verbose_name='Is Company')),
                ('dateSignUp', models.DateField(auto_now=True, verbose_name='Date Signed Up')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'sl_users',
                'permissions': [('read_only', 'Can only read orders'), ('can_modify', 'Can create & modify the orders')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Supplier Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to=settings.AUTH_USER_MODEL, verbose_name='Associated Account')),
            ],
            options={
                'db_table': 'sl_suppliers',
                'ordering': ['name'],
            },
        ),
    ]
